package com.wangjt.calendar.mysql.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CalendarMailremindLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public CalendarMailremindLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNull() {
            addCriterion("EVENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andEventIdIsNotNull() {
            addCriterion("EVENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEventIdEqualTo(String value) {
            addCriterion("EVENT_ID =", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotEqualTo(String value) {
            addCriterion("EVENT_ID <>", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThan(String value) {
            addCriterion("EVENT_ID >", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_ID >=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThan(String value) {
            addCriterion("EVENT_ID <", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLessThanOrEqualTo(String value) {
            addCriterion("EVENT_ID <=", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdLike(String value) {
            addCriterion("EVENT_ID like", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotLike(String value) {
            addCriterion("EVENT_ID not like", value, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdIn(List<String> values) {
            addCriterion("EVENT_ID in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotIn(List<String> values) {
            addCriterion("EVENT_ID not in", values, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdBetween(String value1, String value2) {
            addCriterion("EVENT_ID between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andEventIdNotBetween(String value1, String value2) {
            addCriterion("EVENT_ID not between", value1, value2, "eventId");
            return (Criteria) this;
        }

        public Criteria andRemindIdIsNull() {
            addCriterion("REMIND_ID is null");
            return (Criteria) this;
        }

        public Criteria andRemindIdIsNotNull() {
            addCriterion("REMIND_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRemindIdEqualTo(String value) {
            addCriterion("REMIND_ID =", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdNotEqualTo(String value) {
            addCriterion("REMIND_ID <>", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdGreaterThan(String value) {
            addCriterion("REMIND_ID >", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdGreaterThanOrEqualTo(String value) {
            addCriterion("REMIND_ID >=", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdLessThan(String value) {
            addCriterion("REMIND_ID <", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdLessThanOrEqualTo(String value) {
            addCriterion("REMIND_ID <=", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdLike(String value) {
            addCriterion("REMIND_ID like", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdNotLike(String value) {
            addCriterion("REMIND_ID not like", value, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdIn(List<String> values) {
            addCriterion("REMIND_ID in", values, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdNotIn(List<String> values) {
            addCriterion("REMIND_ID not in", values, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdBetween(String value1, String value2) {
            addCriterion("REMIND_ID between", value1, value2, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindIdNotBetween(String value1, String value2) {
            addCriterion("REMIND_ID not between", value1, value2, "remindId");
            return (Criteria) this;
        }

        public Criteria andRemindStatusIsNull() {
            addCriterion("REMIND_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRemindStatusIsNotNull() {
            addCriterion("REMIND_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRemindStatusEqualTo(String value) {
            addCriterion("REMIND_STATUS =", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusNotEqualTo(String value) {
            addCriterion("REMIND_STATUS <>", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusGreaterThan(String value) {
            addCriterion("REMIND_STATUS >", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusGreaterThanOrEqualTo(String value) {
            addCriterion("REMIND_STATUS >=", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusLessThan(String value) {
            addCriterion("REMIND_STATUS <", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusLessThanOrEqualTo(String value) {
            addCriterion("REMIND_STATUS <=", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusLike(String value) {
            addCriterion("REMIND_STATUS like", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusNotLike(String value) {
            addCriterion("REMIND_STATUS not like", value, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusIn(List<String> values) {
            addCriterion("REMIND_STATUS in", values, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusNotIn(List<String> values) {
            addCriterion("REMIND_STATUS not in", values, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusBetween(String value1, String value2) {
            addCriterion("REMIND_STATUS between", value1, value2, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindStatusNotBetween(String value1, String value2) {
            addCriterion("REMIND_STATUS not between", value1, value2, "remindStatus");
            return (Criteria) this;
        }

        public Criteria andRemindTimeIsNull() {
            addCriterion("REMIND_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRemindTimeIsNotNull() {
            addCriterion("REMIND_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRemindTimeEqualTo(Date value) {
            addCriterion("REMIND_TIME =", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeNotEqualTo(Date value) {
            addCriterion("REMIND_TIME <>", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeGreaterThan(Date value) {
            addCriterion("REMIND_TIME >", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REMIND_TIME >=", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeLessThan(Date value) {
            addCriterion("REMIND_TIME <", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeLessThanOrEqualTo(Date value) {
            addCriterion("REMIND_TIME <=", value, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeIn(List<Date> values) {
            addCriterion("REMIND_TIME in", values, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeNotIn(List<Date> values) {
            addCriterion("REMIND_TIME not in", values, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeBetween(Date value1, Date value2) {
            addCriterion("REMIND_TIME between", value1, value2, "remindTime");
            return (Criteria) this;
        }

        public Criteria andRemindTimeNotBetween(Date value1, Date value2) {
            addCriterion("REMIND_TIME not between", value1, value2, "remindTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 30 17:38:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}