package com.wangjt.calendar.mysql.dao.model;

import java.util.Date;

public class CalendarMailremindLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_mailremind_log.ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_mailremind_log.EVENT_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_mailremind_log.REMIND_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    private String remindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_mailremind_log.REMIND_STATUS
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    private String remindStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_mailremind_log.REMIND_TIME
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    private Date remindTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_mailremind_log.ID
     *
     * @return the value of calendar_mailremind_log.ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_mailremind_log.ID
     *
     * @param id the value for calendar_mailremind_log.ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_mailremind_log.EVENT_ID
     *
     * @return the value of calendar_mailremind_log.EVENT_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_mailremind_log.EVENT_ID
     *
     * @param eventId the value for calendar_mailremind_log.EVENT_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_mailremind_log.REMIND_ID
     *
     * @return the value of calendar_mailremind_log.REMIND_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public String getRemindId() {
        return remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_mailremind_log.REMIND_ID
     *
     * @param remindId the value for calendar_mailremind_log.REMIND_ID
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setRemindId(String remindId) {
        this.remindId = remindId == null ? null : remindId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_mailremind_log.REMIND_STATUS
     *
     * @return the value of calendar_mailremind_log.REMIND_STATUS
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public String getRemindStatus() {
        return remindStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_mailremind_log.REMIND_STATUS
     *
     * @param remindStatus the value for calendar_mailremind_log.REMIND_STATUS
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setRemindStatus(String remindStatus) {
        this.remindStatus = remindStatus == null ? null : remindStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_mailremind_log.REMIND_TIME
     *
     * @return the value of calendar_mailremind_log.REMIND_TIME
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public Date getRemindTime() {
        return remindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_mailremind_log.REMIND_TIME
     *
     * @param remindTime the value for calendar_mailremind_log.REMIND_TIME
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    public void setRemindTime(Date remindTime) {
        this.remindTime = remindTime;
    }
}