package com.wangjt.calendar.mysql.dao.model;

public class CalendarPwd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_pwd.user_id
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_pwd.user_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_pwd.rnum
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    private Integer rnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_pwd.user_id
     *
     * @return the value of calendar_pwd.user_id
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_pwd.user_id
     *
     * @param userId the value for calendar_pwd.user_id
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_pwd.user_pwd
     *
     * @return the value of calendar_pwd.user_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_pwd.user_pwd
     *
     * @param userPwd the value for calendar_pwd.user_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_pwd.rnum
     *
     * @return the value of calendar_pwd.rnum
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public Integer getRnum() {
        return rnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_pwd.rnum
     *
     * @param rnum the value for calendar_pwd.rnum
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    public void setRnum(Integer rnum) {
        this.rnum = rnum;
    }
}