package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarEventReminder;
import com.wangjt.calendar.mysql.dao.model.CalendarEventReminderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEventReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int countByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int deleteByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int insert(CalendarEventReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int insertSelective(CalendarEventReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    List<CalendarEventReminder> selectByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    CalendarEventReminder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") CalendarEventReminder record, @Param("example") CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int updateByExample(@Param("record") CalendarEventReminder record, @Param("example") CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int updateByPrimaryKeySelective(CalendarEventReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Thu Jan 31 09:19:59 CST 2019
     */
    int updateByPrimaryKey(CalendarEventReminder record);
}