package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarMailremindLog;
import com.wangjt.calendar.mysql.dao.model.CalendarMailremindLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarMailremindLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int countByExample(CalendarMailremindLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int deleteByExample(CalendarMailremindLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int insert(CalendarMailremindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int insertSelective(CalendarMailremindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    List<CalendarMailremindLog> selectByExample(CalendarMailremindLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    CalendarMailremindLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") CalendarMailremindLog record, @Param("example") CalendarMailremindLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int updateByExample(@Param("record") CalendarMailremindLog record, @Param("example") CalendarMailremindLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int updateByPrimaryKeySelective(CalendarMailremindLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_mailremind_log
     *
     * @mbggenerated Wed Jan 30 17:38:43 CST 2019
     */
    int updateByPrimaryKey(CalendarMailremindLog record);
}