package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarPwd;
import com.wangjt.calendar.mysql.dao.model.CalendarPwdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarPwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int countByExample(CalendarPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int deleteByExample(CalendarPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int insert(CalendarPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int insertSelective(CalendarPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    List<CalendarPwd> selectByExample(CalendarPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    CalendarPwd selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") CalendarPwd record, @Param("example") CalendarPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int updateByExample(@Param("record") CalendarPwd record, @Param("example") CalendarPwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int updateByPrimaryKeySelective(CalendarPwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_pwd
     *
     * @mbggenerated Mon Jan 21 17:17:54 CST 2019
     */
    int updateByPrimaryKey(CalendarPwd record);
}